services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn contact_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: contact_project.settings
      - key: PYTHON_VERSION
        value: 3.10
